### ISSUE TITLE
glob test fails

### ISSUE THREAD

**Issue by badshah400** [awsteiner/o2scl#8]
o2scl version: 0.922
When building on openSUSE, running make check results in one test failing: `FAIL: general glob test`

Here is the full output from the `src/base/misc.scr` file in the build directory that shows this failing test:
```
test1            test_of_string4  test_of_string7  test_of_string10
test_of_string2  test5            test_of_string8
test_of_string3  test_of_string6  test_of_string9
PASS: general screenify
PASS: general count1
PASS: general count2
PASS: general count3
Whitespace characters: 9 10 11 12 13 32
4.69516e-18 0 3.84407e-18
0  -1.000000e+00
1  -9.975274e-01
2  -8.807971e-01
3  -1.192029e-01
4  -2.472623e-03
5  +0.000000e+00
6  +2.472623e-03
7  +1.192029e-01
8  +8.807971e-01
9  +1.000000e+00
10 -1.000000e+00
11 -9.975274e-01
12 -8.807971e-01
13 -1.192029e-01
14 -2.472623e-03
PASS: general remove_whitespace()
PASS: general remove_whitespace()
PASS: general vec_index 1
PASS: general vec_index 2
PASS: general vec_index 3
PASS: general vec_index 4
PASS: general vec_index 5
PASS: general vec_index 6
PASS: general vec_index 7
PASS: general vec_index 8
FAIL: general glob test
15 tests performed.
At least one test failed.
Last failed test: glob test
```

**Comment by awsteiner** [comment]
Apparently glob_wrapper() isn't sufficiently platform-independent. I'm not sure if this is a POSIX thing or what. It was an experimental function which is not used anyway, so I removed the test and improved the documentation. I'm closing the issue, since the tests pass now, but I've added also it to the list of future improvements. It could be that the best thing to do is have configure.ac detect, in some what, whether or not this sort of function works. Let me know if there is anything else.
